routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes([
    'register'  => false,
    'reset'     => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('designation', 'DesignationController');
    Route::resource('employee', 'EmployeeController');
    Route::get('today-attendance', 'AttendanceController@index')->name('today-attendance');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    public function employee_designation()
    {
        return $this->belongsTo(Designation::class, 'designation_id', 'id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Employee\StoreEmployee;
use App\Models\Designation;
use App\Models\Employee;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('verityDesignationCont')->only(['create', 'store']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Employee::all();
        return view('pages.employee.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $designations = Designation::all();
        return view('pages.employee.create', compact('designations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployee $request)
    {
        $lastEmployeeInfo = Employee::latest()->first();
        if ($lastEmployeeInfo == null) {
            $employeeId = env('EMPLOYEE_FIRST_ID');
        } else {
            $employeeId = $lastEmployeeInfo->employee_id + 1;
        }

        $localAiServer = env('LOCAL_AI_SERVER');
        $empRegiSlug = env('EMP_REGI_API_SLUG');

        try {
            $aiResponse = Http::post($localAiServer . '/' . $empRegiSlug, [
                'company'   => env('COMPANY_SLUG'),
                'user_id'   => $employeeId,
                'file'      => base64_encode(file_get_contents($request->file('employee_image')))
            ]);

            $aiResponseArray = $aiResponse->json();

            if ($aiResponseArray['status'] === 200 && $aiResponseArray['register'] === true) {
                $orginalName =  preg_replace("/\s+/", "_", $request->file('employee_image')->getClientOriginalName());
                $employeeImage = $request->file('employee_image');
                $newEmployee = new Employee;

                $newEmployee->designation_id    = $request->designation_id;
                $newEmployee->employee_id       = $employeeId;
                $newEmployee->employee_name     = $request->employee_name;
                $newEmployee->gender            = $request->gender;
                $newEmployee->employee_image    = $employeeId . '_' . $orginalName;
                $newEmployee->employee_status   = $request->employee_status;

                $saveEmployee = $newEmployee->save();

                $employeeImage->move(storage_path('/app/public/images') . '/', $employeeId . '_' . $orginalName);

                if ($saveEmployee) {
                    session()->flash('success', 'Employee Added Successfully');
                    return redirect()->route('employee.index');
                } else {
                    session()->flash('error', 'Something Happend Wrong');
                    return redirect()->back();
                }
            }

            if ($aiResponseArray['status'] === 500) {
                session()->flash('error', 'Something Happend Wrong');
                return redirect()->back();
            }
        } catch (Exception $error) {
            session()->flash('error', 'Error in AI Server. Try again');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        //
    }
}

resources/views/pages/employee/create.blade.php
@extends('layouts.admin-master')

@section('title', 'Create Employee')

@section('content')
<div class="container  content-area">
    <div class="section">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/dashboard') }}"><i class="fe fe-life-buoy mr-1"></i> Dashboard</a></li>
                <li class="breadcrumb-item" aria-current="page">Create Employee</li>
            </ol>
        </div>

        <div class="row">
            <div class="col-md">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Create Employee</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('employee.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-label">{{ __('Employee Name') }} </label>
                                        <input type="text" class="form-control @error('employee_name') is-invalid @enderror" name="employee_name" placeholder="{{ __('Employee Name') }}" value="{{ old('employee_name') }}" required>
                                        @error('employee_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-label">{{ __('Employee Designation') }}</label>
                                        <select name="designation_id" class="form-control @error('designation_id') is-invalid @enderror select2 custom-select" data-placeholder="Choose one" required>
                                            <option label="{{ __('Choose one') }}"></option>
                                            @foreach ($designations as $designation)
                                            <option value="{{$designation->id}}">{{$designation->designation}}</option>
                                            @endforeach
                                        </select>
                                        @error('designation_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="form-label">{{ __('Employee Gender') }}</div>
                                        <div class="custom-controls-stacked form-check-inline">
                                            <label class="custom-control custom-radio">
                                                <input type="radio" class="custom-control-input" name="gender" value="1" checked required>
                                                <span class="custom-control-label">{{ __('Male') }}</span>
                                            </label>&nbsp;&nbsp;&nbsp;&nbsp;
                                            <label class="custom-control custom-radio">
                                                <input type="radio" class="custom-control-input" name="gender" value="2">
                                                <span class="custom-control-label">{{ __('Female') }}</span>
                                            </label>
                                        </div>
                                        @error('gender')
                                        <span class="invalid-feedback" role="alert" style="display: block;">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="form-label">{{ __('Employee Image') }}</div>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="employee_image" accept="image/jpg, image/jpeg, image/png" required>
                                            <label class="custom-file-label">{{ __('Choose file') }}</label>
                                        </div>
                                        @error('employee_image')
                                        <span class="invalid-feedback" role="alert" style="display: block;">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="form-label">{{ __('Employee Status') }}</label>
                                        <select name="employee_status" class="form-control @error('employee_status') is-invalid @enderror select2 custom-select" data-placeholder="Choose one" required>
                                            <option label="Choose one"></option>
                                            <option value="0">{{ __('Inactive Employee') }}</option>
                                            <option value="1">{{ __('Active Employee') }}</option>
                                        </select>
                                        @error('employee_status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <button type="submit" class="btn btn-success btn-block">{{ __('Save Employee') }}</button>
                                </div>
                                <div class="col-md-6">
                                    <a href="{{ route('employee.index') }}" class="btn btn-warning btn-block">{{ __('Cancel') }}</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" href="{{ asset('plugins/sweet-alert/sweetalert.css') }}" />
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
@if(session('error'))
<script>
    $(document).ready(function() {
        Swal.fire({
            title: "{{ session('error') }}",
            showClass: {
                popup: 'animate__animated animate__fadeInDown'
            },
            hideClass: {
                popup: 'animate__animated animate__fadeOutUp'
            }
        })
    });
</script>
@endif
@if(session('success'))
<script>
    $(document).ready(function() {
        Swal.fire({
            title: "{{ session('error') }}",
            showClass: {
                popup: 'animate__animated animate__fadeInDown'
            },
            hideClass: {
                popup: 'animate__animated animate__fadeOutUp'
            }
        })
    });
</script>
@endif
@endsection

resources/views/pages/employee/index.blade.php
@extends('layouts.admin-master')

@section('title', 'Employee')

@section('content')
<div class="container  content-area">
    <div class="section">
        <div class="page-header">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/dashboard') }}"><i class="fe fe-life-buoy mr-1"></i> Dashboard</a></li>
                <li class="breadcrumb-item" aria-current="page">Employee List</li>
            </ol>
            <div class="ml-auto">
                <a href="{{ route('employee.create') }}" class="btn btn-primary btn-icon btn-sm text-white mr-2">
                    <span>
                        <i class="fe fe-plus"></i>
                    </span> Add Employee
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Employee List Table</h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table card-table table-vcenter text-nowrap">
                            <thead>
                                <tr>
                                    <th>Sl.</th>
                                    <th>Designation</th>
                                    <th>Employee Id</th>
                                    <th>Employee Name</th>
                                    <th>Employee Image</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($datas as $data)
                                <tr id="employeeId-{{ $data->id }}">
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $data->employee_designation->designation }}</td>
                                    <td>{{ $data->employee_id }}</td>
                                    <td>{{ $data->employee_name }}</td>
                                    <td><img style="width: 30px; height: 30px" src="{{url('storage/images', $data->employee_image)}}" alt="{{ $data->employee_image }}" /></td>
                                    <td>
                                        <div class="btn-list">
                                            <a href="" class="btn btn-icon btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit Device Type"><i class="fe fe-edit"></i></a>
                                            <button type="button" data-id="{{ $data->id }}" class="btn btn-icon btn-danger btn-sm delete-device-type" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete Device Type"><i class="fe fe-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <th colspan="6" class="text-center">No Employee Added Now.</th>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" href="{{ asset('plugins/sweet-alert/sweetalert.css') }}" />
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
@if(session('success'))
<script>
    $(document).ready(function() {
        Swal.fire('Congratulations!', "{{ session('success') }}", 'success');
    });
</script>
@endif
@endsection