routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes([
    'register'  => false,
    'reset'     => false
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('designation', 'DesignationController');
    Route::resource('employee', 'EmployeeController');
    Route::get('today-attendance', 'AttendanceController@index')->name('today-attendance');
});

resources/views/page_pertials/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-md-12 col-sm-12 text-center">
                Copyright © 2020 to {{ date('Y') }}. Developed by <a target="blank" href="http://cpsdbd.com/">CPSD</a> All rights reserved.
            </div>
        </div>
    </div>
</footer>

resources/views/page_pertials/loader.blade.php
 <div id="global-loader">
     <img src="{{ asset('img/loader.svg') }}" class="loader-img" alt="Loader">
 </div>

resources/views/page_pertials/nav-menu.blade.php
<div class="sticky">
    <div class="horizontal-main hor-menu clearfix ">
        <div class="horizontal-mainwrapper container clearfix">
            <nav class="horizontalMenu clearfix">
                <ul class="horizontalMenu-list">
                    <li aria-haspopup="true"><a href="{{ route('dashboard') }}" class=""><i class="fe fe-grid"></i> Dashboard</a></li>
                    <li aria-haspopup="true"><a href="#" class="sub-icon"><i class="fa fa-group"></i> Employee <i class="fa fa-angle-down horizontal-icon"></i></a>
                        <ul class="sub-menu">
                            <li aria-haspopup="true"><a href="{{ route('designation.index') }}">Designation</a></li>
                            <li aria-haspopup="true"><a href="{{ route('employee.index') }}"> Employee</a></li>
                        </ul>
                    </li>
                    <li aria-haspopup="true"><a href="#" class="sub-icon"><i class="fa fa-group"></i> Attendance <i class="fa fa-angle-down horizontal-icon"></i></a>
                        <ul class="sub-menu">
                            <li aria-haspopup="true"><a href="{{ route('today-attendance') }}">Today Attendance</a></li>
                            <li aria-haspopup="true"><a href="#"> Attendance Report</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

resources/views/page_pertials/nav-top.blade.php
<div class="header top-header hor-topheader" style="z-index: 99;">
    <div id="particles-js" class="zindex1"></div>
    <div class="container">
        <div class="d-flex header-nav">
            <a id="horizontal-navtoggle" class="animated-arrow hor-toggle"><span></span></a>
            <div class="color-headerlogo">
                <a class="header-desktop" href="{{ route('dashboard') }}"></a>
                <a class="header-mobile" href="{{ route('dashboard') }}"></a>
            </div>

            <a class="header-brand header-brand2 d-none d-lg-block  align-items-center justify-content-center" href="{{ route('dashboard') }}">
                <a class="header-desktop" href="{{ route('dashboard') }}"></a>
            </a>
            <div class="d-flex order-lg-2 ml-auto header-right-icons header-search-icon">
                <div class="dropdown  header-fullscreen">
                    <a class="nav-link icon full-screen-link nav-link-bg" id="fullscreen-button">
                        <i class="fe fe-minimize"></i>
                    </a>
                </div>
                <div class="dropdown header-user">
                    <a href="#" class="nav-link icon" data-toggle="dropdown">
                        <span><img src="{{ asset('img/avater.jpg') }}" alt="profile-user" class="avatar brround cover-image mb-0 ml-0"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                        <div class=" dropdown-header noti-title text-center border-bottom p-3">
                            <div class="header-usertext">
                                <h5 class="mb-1">{{Auth::user()->name}}</h5>
                                <p class="mb-0">{{Auth::user()->email}}</p>
                            </div>
                        </div>
                        <a class="dropdown-item" href="profile.html">
                            <i class="mdi mdi-account-outline mr-2"></i> <span>My profile</span>
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="mdi mdi-settings mr-2"></i> <span>Settings</span>
                        </a>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="mdi  mdi-logout-variant mr-2"></i> <span>Logout</span>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>